# Generated by Django 4.0.5 on 2024-04-23 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 23, 10, 31, 32, 52348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2024, 4, 23, 10, 31, 32, 50349, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2024, 4, 23, 10, 31, 32, 50349, tzinfo=utc)),
        ),
    ]
