# Generated by Django 4.0.5 on 2024-04-23 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_event_article_allowed_alter_article_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 23, 14, 10, 50, 921439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2024, 4, 23, 14, 10, 50, 919439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2024, 4, 23, 14, 10, 50, 919439, tzinfo=utc)),
        ),
    ]
