# Generated by Django 4.0.5 on 2024-04-27 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_date_alter_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 27, 11, 1, 47, 794723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2024, 4, 27, 11, 1, 47, 792720, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2024, 4, 27, 11, 1, 47, 792720, tzinfo=utc)),
        ),
    ]
